#!/usr/bin/env bash

shopt -s dotglob extglob globstar nullglob

if [[ $0 == /* ]]; then
    location=${0%/*}
else
    location=$PWD/${0#./}
    location=${location%/*}
fi

for file in "$location"/**/*; do
    bare="${file#$location/}"

    case "$bare" in
        .git|.git/*|.gitignore|.gitmodules|setup|*/.gitkeep|README.md) continue ;;
    esac

    if [[ -d "$file" ]] && ! [[ -L "$file" ]]; then
        if [[ -L ~/"$bare" ]]; then
            echo "Removing $bare"
            rm ~/"$bare"
        fi
        mkdir -m755 -p ~/"$bare"
    else
        link=$HOME/$bare
        real_link=$(readlink -f "$link")
        real_file=$(readlink -f "$file")
        # If we already linked this file due to a directory symlink inside the
        # dotfiles, don't try and link it again (see issue #1)
        [[ $real_link != "$real_file" ]] && echo "Linking $file to ~/$bare" && ln -sfn "$file" ~/"$bare"
    fi
done

deleted=()
if [[ -f ~/.dfsha ]]; then
    mapfile -t deleted < <(git diff --name-status "$(<~/.dfsha)" HEAD | grep -v .vim/bundle | sed -n 's/^D[[:blank:]]//p' | sed 's/\.gpg$//')
fi

if (( "${#deleted[@]}" )); then
    ( cd && rm -r "${deleted[@]}" )
fi

# We check systemctl status as it's possible for other users we don't have a
# session
if PAGER=cat systemctl --user >/dev/null 2>&1; then
    systemctl --user daemon-reload
    systemctl --user reset-failed
fi

git rev-parse HEAD > ~/.dfsha


if [[ ! -d ~/.oh-my-zsh ]]; then
    echo Installing OMZ
    git clone http://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
fi
if [[ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]]; then
    echo Installing zsh autosuggestions
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

# Vim plugins
mkdir -p ~/.vim/bundle
if [[ ! -d ~/.vim/bundle/Vundle.vim ]]; then
    echo Installing Vundle
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

# Vim plugins
mkdir -p ~/.apps
if [[ ! -d ~/.apps/fzf ]]; then
    echo Installing fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.apps/fzf
    ~/.apps/fzf/install --bin
    ln -s ~/.apps/fzf/bin/fzf ~/.local/bin/fzf
fi
