#!/usr/bin/env bash

# Setup vim-plug and install plugins
VIM_PLUG="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
if [ ! -f $VIM_PLUG ]; then
	echo Initializing vim-plug
	curl -fLo "$VIM_PLUG" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nvim --headless +PlugInstall +qa
