#!/usr/bin/env bash
set -e

DIR_NAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$DIR_NAME/scripts/bootstrap_dotfiles.sh
source $DIR_NAME/.venv/bin/activate
python $DIR_NAME/symlink_dotfiles.py
bash $DIR_NAME/scripts/setup/nvim.sh
