local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>fF", builtin.find_files, {})
vim.keymap.set("n", "<leader>ff", builtin.git_files, {})
vim.keymap.set("n", "<leader>t", builtin.buffers, {})
vim.keymap.set("n", "<leader>fg", builtin.buffers, {})
vim.keymap.set("n", "<C-t>", builtin.git_files, {})
