return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		config = function()
			local wk = require("which-key")

			wk.setup({
				plugins = {
					marks = true,
					registers = true,
					spelling = {
						enabled = true,
						suggestions = 20,
					},
					presets = {
						operators = false,
						motions = true,
						text_objects = true,
						windows = true,
						nav = true,
						z = true,
						g = true,
					},
				},
				icons = {
					breadcrumb = "»",
					separator = "➜",
					group = "+",
				},
				keys = {
					scroll_down = "<c-d>",
					scroll_up = "<c-u>",
				},
				win = {
					border = "rounded",
					position = "bottom",
					margin = { 1, 0, 1, 0 },
					padding = { 1, 2, 1, 2 },
					winblend = 0,
					zindex = 1000,
				},
				layout = {
					height = { min = 4, max = 25 },
					width = { min = 20, max = 50 },
					spacing = 3,
					align = "left",
				},
				replace = {
					["<space>"] = "SPC",
					["<cr>"] = "RET",
					["<tab>"] = "TAB",
				},
				show_help = true,
				show_keys = true,
				-- Remove deprecated options (motions, hidden, operators, triggers, etc.)
			})

			-- New spec format
			wk.add({
				{ '<leader>"', desc = "Comment Block" },
				{ "<leader>/", desc = "Comment Line" },
				{ "<leader>E", desc = "Focus Explorer" },
				{ "<leader>Y", desc = "Copy Line to System" },
				{ "<leader>e", desc = "File Explorer" },
				{ "<leader>r", desc = "Reload Config" },
				{ "<leader>y", desc = "Copy to System" },
				{ "<leader>c", group = "Code" },
				{ "<leader>d", group = "Debug" },
				{ "<leader>f", group = "Find/Search" },
				{ "<leader>fF", desc = "All Files" },
				{ "<leader>fS", desc = "Workspace Symbols" },
				{ "<leader>fb", desc = "Buffer Search" },
				{ "<leader>fc", desc = "Commands" },
				{ "<leader>fd", desc = "Diagnostics" },
				{ "<leader>ff", desc = "Git Files" },
				{ "<leader>fg", desc = "Live Grep" },
				{ "<leader>fh", desc = "Help Tags" },
				{ "<leader>fk", desc = "Keymaps" },
				{ "<leader>fl", desc = "Location List" },
				{ "<leader>fm", desc = "Marks" },
				{ "<leader>fo", desc = "Recent Files" },
				{ "<leader>fq", desc = "Quickfix" },
				{ "<leader>fr", desc = "References" },
				{ "<leader>fs", desc = "Document Symbols" },
				{ "<leader>fw", desc = "Find Word" },
				{ "<leader>g", group = "Git" },
				{ "<leader>gA", desc = "Git Add All" },
				{ "<leader>gD", desc = "Open Diffview" },
				{ "<leader>gG", desc = "Git Status (Fugitive)" },
				{ "<leader>gH", desc = "File History (All)" },
				{ "<leader>gP", desc = "Git Pull" },
				{ "<leader>gR", desc = "Refresh Diffview" },
				{ "<leader>gX", desc = "Close Diffview" },
				{ "<leader>ga", desc = "Git Add Current File" },
				{ "<leader>gb", desc = "Branches (Telescope)" },
				{ "<leader>gbl", desc = "Git Blame" },
				{ "<leader>gc", desc = "Commits (Telescope)" },
				{ "<leader>gcm", desc = "Git Commit" },
				{ "<leader>gco", desc = "Git Checkout" },
				{ "<leader>gd", desc = "Git Diff" },
				{ "<leader>gg", desc = "Open Neogit" },
				{ "<leader>gh", desc = "Current File History" },
				{ "<leader>gl", desc = "Git Log" },
				{ "<leader>gp", desc = "Git Push" },
				{ "<leader>gs", desc = "Status (Telescope)" },
				{ "<leader>v", group = "LSP" },
				{ "<leader>vca", desc = "Code Action" },
				{ "<leader>vd", desc = "Diagnostics Float" },
				{ "<leader>vrn", desc = "Rename" },
				{ "<leader>vrr", desc = "References" },
				{ "<leader>vws", desc = "Workspace Symbol" },
				{ "<leader>S", desc = "Toggle Spectre" },
				{ "<leader>s", group = "Search/Replace" },
				{ "<leader>sp", desc = "Search in File" },
				{ "<leader>sw", desc = "Search Word" },
				{ "<leader>p", group = "Plugin/Project" },
				{ "<leader>pm", desc = "Mason" },
				{ "<leader>pv", desc = "File Manager" },
				{ "<leader>t", desc = "Find Buffers" },
				{ "K", desc = "Hover Documentation" },
				{ "[", group = "Previous" },
				{ "[d", desc = "Diagnostic" },
				{ "]", group = "Next" },
				{ "]d", desc = "Diagnostic" },
				{ "g", group = "Go to" },
				{ "gd", desc = "Definition" },
			})
		end,
	},
}
