# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# If Git is slow with retrieving the current state,
# don't wait too long before exiting
command_timeout = 100

format = """
$username\
$hostname\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[username]
style_user = "bg:#a3aed2 fg:#090c0c"
format = "[$user]($style)"

[hostname]
style = "bg:#a3aed2 fg:#090c0c"
format = "[ @ $hostname]($style)"
trim_at = ".companyname.com"
ssh_symbol = ""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 0
fish_style_pwd_dir_length = 1

[time]
disabled = false
time_format = "%T" # hour:minute:second Format
style = "bg:#1d2230"
format = "[[$time](fg:#a0a9cb bg:#1d2230)]($style)"

[git_branch]
symbol = ""
style = "bg:#394260"
format = "[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)"

[git_status]
# Disabled because git status can be slow
disabled = true
style = "bg:#394260"
format = "[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
disabled = true
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[package]
disabled = false
